version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8880:8880"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"